
### ================================
### 1️⃣ enviar notificación
### ================================

POST http://localhost:8000/operarios/notificaciones?user_id=1
Content-Type: application/json

{
    "obra_id": 1,
    "tipo": "incidencia",
    "mensaje": "holaaaaa que tal chicas?"
}

### caso 1: notificación tuya
GET http://localhost:8000/operarios/notificaciones/17?user_id=1

### caso 2: notificación que no existe
GET http://localhost:8000/operarios/notificaciones/999?user_id=1

### caso 3: notificación de otro usuario
GET http://localhost:8000/operarios/notificaciones/17?user_id=99